name: riverpod_infinite_scroll_pagination
description: An infinite scroll pagination using Riverpod (Lazy loading pages as the user scrolls to the end of the list).
version: 1.0.2
homepage: https://github.com/hafees/riverpod_infinite_scroll
repository: https://github.com/hafees/riverpod_infinite_scroll
issue_tracker: https://github.com/hafees/riverpod_infinite_scroll/issues

topics:
  - riverpod
  - pagination
  - scrolling-pagination
  - infinite-scroll-pagination

environment:
  sdk: ">=3.1.2 <4.0.0"

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  skeletonizer: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
  riverpod_annotation: ^2.3.0
  test: ^1.24.3
  riverpod_generator: ^2.3.6
  envied_generator: ^0.5.1
  mocktail: ^1.0.1

flutter:
